trading:
  tickers:
  - ACS.MC
  - AIXA.DE
  - AKAM
  - ALB
  - AMAT
  - ANA.MC
  - APA
  - ASML
  - ASML.AS
  - BEZ.L
  - BG
  - BKR
  - BP.L
  - CAT
  - CF
  - CIEN
  - CNA.L
  - COHR
  - COP
  - CTRA
  - CVX
  - DELL
  - DIA.MC
  - DOW
  - DVN
  - EDV.L
  - EIX
  - ENG.MC
  - ENGI.PA
  - ENI.MI
  - ENR.DE
  - EOG
  - EQIX
  - ETR
  - FANG
  - FCX
  - FDX
  - FIX
  - FORTUM.HE
  - GALP.LS
  - GEV
  - GLEN.L
  - GLW
  - GSK.L
  - HAL
  - HII
  - INTC
  - IPN.PA
  - JBHT
  - JNJ
  - KEYS
  - KLAC
  - LITE
  - LMT
  - LPP.WA
  - LRCX
  - LYB
  - MEL.MC
  - MPC
  - MRK
  - MRNA
  - MRVL
  - MU
  - NEM
  - NHY.OL
  - NOKIA.HE
  - ODFL
  - OMV.VI
  - ORA.PA
  - OXY
  - PRY.MI
  - PSX
  - PWR
  - REP.MC
  - RIO.L
  - ROST
  - RWE.DE
  - SAND.ST
  - SATS
  - SDR.L
  - SHEL.L
  - SLB
  - SNDK
  - SSE.L
  - STX
  - TELIA.ST
  - TER
  - TGS.OL
  - TIT.MI
  - TPL
  - TRGP
  - TTE.PA
  - VACN.SW
  - VK.PA
  - VLO
  - VRT
  - WBD
  - WDC
  - XOM
  - YAR.OL
  cash_parking_etfs:
  - XEON.DE
  - EUN3.DE
